/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.challenge_backend;

/**
 *
 * @author emmme
 */
public class challengeDeDivisas extends javax.swing.JFrame {

    private double fin1;
    private double temp0;

    /**
     * Creates new form challengeDeDivisas
     */
    public challengeDeDivisas() {
        initComponents();
    }
    String list1;
    String list2;
    double factor1;
    double factor2;
    double resultadoDivisas;
    double fin0;
    int temp1;
    int temp2;
//Tasa 1000 divisas a pesos mexicanos
    double USD = 18.44;
    double EUR = 19.64;
    double LIB = 22.34;
//Tasa 1000 divisas a pesos mexicanos
    double YEN = 136.73 / 1000;
    double WON = 14.13922 / 1000;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        listaOrigen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        listaConvertir = new javax.swing.JComboBox<>();
        botonConversion = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        temperatura1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "LIB", "YEN", "WON", "MEX" }));
        listaOrigen.setSelectedItem("");
        listaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaOrigenActionPerformed(evt);
            }
        });
        desktopPane.add(listaOrigen);
        listaOrigen.setBounds(20, 100, 150, 22);

        jLabel1.setText("Conversor de divisas.");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(40, 10, 130, 16);

        jLabel2.setText("Seleccione la divisa origen.");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(20, 80, 150, 16);

        jLabel3.setText("Seleccione la divisa destino.");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(20, 140, 170, 16);

        listaConvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "LIB", "YEN", "WON", "MEX" }));
        desktopPane.add(listaConvertir);
        listaConvertir.setBounds(20, 160, 150, 22);

        botonConversion.setText("Convertir divisas");
        botonConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConversionActionPerformed(evt);
            }
        });
        desktopPane.add(botonConversion);
        botonConversion.setBounds(30, 200, 130, 23);

        resultado.setEditable(false);
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        desktopPane.add(resultado);
        resultado.setBounds(10, 240, 360, 22);

        jLabel4.setText("Introduzca el monto a convertir.");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(20, 30, 180, 16);

        monto.setText("0");
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        desktopPane.add(monto);
        monto.setBounds(20, 50, 120, 22);

        jLabel5.setText("Conversor temperatura.");
        desktopPane.add(jLabel5);
        jLabel5.setBounds(370, 20, 130, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        desktopPane.add(jComboBox1);
        jComboBox1.setBounds(480, 50, 72, 22);

        temperatura1.setText("0");
        desktopPane.add(temperatura1);
        temperatura1.setBounds(390, 50, 64, 22);

        jButton1.setText("Convertir temperatura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton1);
        jButton1.setBounds(390, 120, 160, 23);

        jTextField3.setEditable(false);
        desktopPane.add(jTextField3);
        jTextField3.setBounds(370, 160, 190, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F" }));
        desktopPane.add(jComboBox2);
        jComboBox2.setBounds(480, 90, 72, 22);

        jLabel6.setText("Convertir a:");
        desktopPane.add(jLabel6);
        jLabel6.setBounds(400, 90, 70, 16);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaOrigenActionPerformed
        
    }//GEN-LAST:event_listaOrigenActionPerformed

    private void botonConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConversionActionPerformed
        // TODO add your handling code here:
        list1 = listaOrigen.getSelectedItem().toString();
        list2 = listaConvertir.getSelectedItem().toString();
        double fin0 = Double.parseDouble(monto.getText());
        
          if (list1.equals(list2)){
            factor2 = fin0;
        } else if ("USD".equals(list1)) {
            factor1 = USD*fin0;
        } else if ("EUR".equals(list1)) {
            factor1 = EUR*fin0;
        } else if ("LIB".equals(list1)) {
            factor1 = LIB*fin0;
        } else if ("WON".equals(list1)) {
            factor1 = WON*fin0;
        } else if ("YEN".equals(list1)) {
            factor1 = YEN*fin0;
        } else if ("MEX".equals(list1)) {
            factor1 = fin0;
        }
        
          if (list1.equals(list2)){
            factor2 = fin0;
        } else if ("USD".equals(list2)) {
            factor2 = factor1/USD;
        } else if ("EUR".equals(list2)) {
            factor2 = factor1/EUR;
        } else if ("LIB".equals(list2)) {
            factor2 = factor1/LIB;
        } else if ("WON".equals(list2)) {
            factor2 = factor1/WON;
        } else if ("YEN".equals(list2)) {
            factor2 = factor1/YEN;
        } else if ("MEX".equals(list2)) {
            factor2 = factor1;
        }
        
        resultado.setText("Usted tiene " + factor2 + " " + list2);
        
        
        
    }//GEN-LAST:event_botonConversionActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        temp1 = jComboBox1.getSelectedIndex();
        temp2 = jComboBox2.getSelectedIndex();
        if (temp2 == temp1){
            jTextField3.setText(Double.valueOf(temperatura1.getText()) + " " + jComboBox2.getSelectedItem());
        }   
        if (temp1 == 0 && temp2 == 1) {
            jTextField3.setText((((Double.parseDouble(temperatura1.getText())*9)/5) + 32) + " " + jComboBox2.getSelectedItem());
        }   
        if (temp1 == 1 && temp2 == 0) {
            jTextField3.setText(((5*(Double.parseDouble(temperatura1.getText()) - 32))/ 9) + " " + jComboBox2.getSelectedItem());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(challengeDeDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(challengeDeDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(challengeDeDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(challengeDeDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new challengeDeDivisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConversion;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox<String> listaConvertir;
    private javax.swing.JComboBox<String> listaOrigen;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField monto;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField resultado;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField temperatura1;
    // End of variables declaration//GEN-END:variables

    private void setText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
